### ISSUE TITLE
[BUG] powerscale provider v1.2.0 fails to reorder AccessZone auth providers on apply.

### ISSUE THREAD

**Issue by petew-nfx** [dell/dell-terraform-providers#14]
**Provider information**
```
terraform {
   required_providers {
    powerscale = {
      source = "registry.terraform.io/dell/powerscale"
      version = "1.2.0"
    }
  }
}
```

Start with System zone:
```
resource "powerscale_accesszone" "System" {
    custom_auth_providers       = [
          "lsa-local-provider:System",
          "lsa-file-provider:System",
    ]
    groupnet                    = "groupnet0"
    name                        = "System"
    path                        = "/ifs"
}
```
Running `terraform plan` reports **No changes**.

Switch `custom_auth_providers` order:
```
resource "powerscale_accesszone" "System" {
    custom_auth_providers       = [
          "lsa-file-provider:System",
          "lsa-local-provider:System",
    ]
    groupnet                    = "groupnet0"
    name                        = "System"
    path                        = "/ifs"
}
```

`terraform plan` reports the desired changes:
```
...
      ~ custom_auth_providers       = [
          - "lsa-local-provider:System",
            "lsa-file-provider:System",
          + "lsa-local-provider:System",
        ]
...
```

Running `terraform apply` reports the changes are made, but the cluster shows they have not been and `terraform plan` still shows the desired changes.

**Comment by forrestxia** [comment]
@tanh17 please check this issue report and improve the test scenarios. thanks!

@NavisJ Hi Jason, please check this community reported issue. thanks!

**Comment by NavisJ** [comment]
@petew-nfx Thank you for reporting the issue and providing the details.

Based on the information you provided, it appears that the root cause of the problem lies in the incorrect value check of list field type. To address the issue, we will need to make changes on the value comparison function of list type. Once the adjustments are implemented, the reorder operation should work as intended. Our team will work diligently to incorporate these changes and fix the issue as soon as possible. 

If you have any further questions or concerns, please let us know. Thank you!

**Comment by petew-nfx** [comment]
v.1.3.0 has fixed the issue. Thank you!
